-- MySQL Script generated by MySQL Workbench
-- Sun Mar 14 19:19:53 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `univacinema` DEFAULT CHARACTER SET utf8 ;
USE `univacinema` ;

-- -----------------------------------------------------
-- Table `univacinema`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `univacinema`.`user` (
  `userId` INT NOT NULL AUTO_INCREMENT,
  `userName` VARCHAR(45) NOT NULL,
  `userPassword` VARCHAR(45) NOT NULL,
  `userStatus` TINYINT NOT NULL,
  `userCreatedAt` VARCHAR(45) NOT NULL,
  `userUpdatedAt` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`userId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `univacinema`.`movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `univacinema`.`movie` (
  `movieId` INT NOT NULL AUTO_INCREMENT,
  `movieName` VARCHAR(45) NOT NULL,
  `movieDirector` VARCHAR(45) NOT NULL,
  `movieProducer` VARCHAR(45) NOT NULL,
  `movieClassification` VARCHAR(45) NOT NULL,
  `movieDuration` INT NOT NULL,
  `movieStatus` TINYINT NOT NULL,
  `movieCreatedAt` VARCHAR(45) NOT NULL,
  `movieUpdatedAt` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`movieId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `univacinema`.`room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `univacinema`.`room` (
  `roomId` INT NOT NULL AUTO_INCREMENT,
  `roomNumber` INT NOT NULL,
  `roomStatus` TINYINT NOT NULL,
  `roomCreatedAt` VARCHAR(45) NOT NULL,
  `roomUpdatedAt` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`roomId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `univacinema`.`schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `univacinema`.`schedule` (
  `scheduleId` INT NOT NULL AUTO_INCREMENT,
  `scheduleStart` VARCHAR(45) NOT NULL,
  `scheduleEnd` VARCHAR(45) NOT NULL,
  `scheduleStatus` TINYINT NOT NULL,
  `scheduleCreatedAt` VARCHAR(45) NOT NULL,
  `scheduleUpdatedAt` VARCHAR(45) NOT NULL,
  `roomId` INT NOT NULL,
  PRIMARY KEY (`scheduleId`, `roomId`),
  INDEX `fk_schedule_room1_idx` (`roomId` ASC) ,
  CONSTRAINT `fk_schedule_room1`
    FOREIGN KEY (`roomId`)
    REFERENCES `univacinema`.`room` (`roomId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `univacinema`.`state`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `univacinema`.`state` (
  `stateId` INT NOT NULL AUTO_INCREMENT,
  `stateName` VARCHAR(45) NOT NULL,
  `stateStatus` TINYINT NOT NULL,
  `stateCreatedAt` VARCHAR(45) NOT NULL,
  `stateUpdatedAt` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`stateId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `univacinema`.`municipality`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `univacinema`.`municipality` (
  `municipalityId` INT NOT NULL AUTO_INCREMENT,
  `municipalityName` VARCHAR(45) NOT NULL,
  `municipalityStatus` TINYINT NOT NULL,
  `municipalityCreatedAt` VARCHAR(45) NOT NULL,
  `municipalityUpdatedAt` VARCHAR(45) NOT NULL,
  `stateId` INT NOT NULL,
  PRIMARY KEY (`municipalityId`, `stateId`),
  INDEX `fk_municipality_state_idx` (`stateId` ASC),
  CONSTRAINT `fk_municipality_state`
    FOREIGN KEY (`stateId`)
    REFERENCES `univacinema`.`state` (`stateId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `univacinema`.`movie_schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `univacinema`.`movie_schedule` (
  `movieId_fk` INT NOT NULL,
  `scheduleId_fk` INT NOT NULL,
  `roomId_fk` INT NOT NULL,
  PRIMARY KEY (`movieId_fk`, `scheduleId_fk`, `roomId_fk`),
  INDEX `fk_movie_has_schedule_schedule1_idx` (`scheduleId_fk` ASC, `roomId_fk` ASC) ,
  INDEX `fk_movie_has_schedule_movie1_idx` (`movieId_fk` ASC) ,
  CONSTRAINT `fk_movie_has_schedule_movie1`
    FOREIGN KEY (`movieId_fk`)
    REFERENCES `univacinema`.`movie` (`movieId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movie_has_schedule_schedule1`
    FOREIGN KEY (`scheduleId_fk` , `roomId_fk`)
    REFERENCES `univacinema`.`schedule` (`scheduleId` , `roomId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `univacinema`.`movie_location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `univacinema`.`movie_location` (
  `municipalityId_fk` INT NOT NULL,
  `stateId_fk` INT NOT NULL,
  `movieId_fk` INT NOT NULL,
  `scheduleId_fk` INT NOT NULL,
  `roomId_fk` INT NOT NULL,
  PRIMARY KEY (`municipalityId_fk`, `stateId_fk`, `movieId_fk`, `scheduleId_fk`, `roomId_fk`),
  INDEX `fk_municipality_has_movie_has_schedule_movie_has_schedule1_idx` (`movieId_fk` ASC, `scheduleId_fk` ASC, `roomId_fk` ASC) ,
  INDEX `fk_municipality_has_movie_has_schedule_municipality1_idx` (`municipalityId_fk` ASC, `stateId_fk` ASC),
  CONSTRAINT `fk_municipality_has_movie_has_schedule_municipality1`
    FOREIGN KEY (`municipalityId_fk` , `stateId_fk`)
    REFERENCES `univacinema`.`municipality` (`municipalityId` , `stateId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_municipality_has_movie_has_schedule_movie_has_schedule1`
    FOREIGN KEY (`movieId_fk` , `scheduleId_fk` , `roomId_fk`)
    REFERENCES `univacinema`.`movie_schedule` (`movieId_fk` , `scheduleId_fk` , `roomId_fk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `univacinema`.`user_select_movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `univacinema`.`user_select_movie` (
  `municipalityId_fk` INT NOT NULL,
  `stateId_fk` INT NOT NULL,
  `movieId_fk` INT NOT NULL,
  `scheduleId_fk` INT NOT NULL,
  `roomId_fk` INT NOT NULL,
  `userId_fk` INT NOT NULL,
  PRIMARY KEY (`municipalityId_fk`, `stateId_fk`, `movieId_fk`, `scheduleId_fk`, `roomId_fk`, `userId_fk`),
  INDEX `fk_municipality_has_movie_has_schedule_has_user_user1_idx` (`userId_fk` ASC) ,
  INDEX `fk_municipality_has_movie_has_schedule_has_user_municipalit_idx` (`municipalityId_fk` ASC, `stateId_fk` ASC, `movieId_fk` ASC, `scheduleId_fk` ASC, `roomId_fk` ASC) ,
  CONSTRAINT `fk_municipality_has_movie_has_schedule_has_user_municipality_1`
    FOREIGN KEY (`municipalityId_fk` , `stateId_fk` , `movieId_fk` , `scheduleId_fk` , `roomId_fk`)
    REFERENCES `univacinema`.`movie_location` (`municipalityId_fk` , `stateId_fk` , `movieId_fk` , `scheduleId_fk` , `roomId_fk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_municipality_has_movie_has_schedule_has_user_user1`
    FOREIGN KEY (`userId_fk`)
    REFERENCES `univacinema`.`user` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
