-- MySQL Script generated by MySQL Workbench
-- Tue Mar 23 19:05:43 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `userId` INT NOT NULL AUTO_INCREMENT,
  `userName` VARCHAR(45) NOT NULL,
  `userPassword` VARCHAR(45) NOT NULL,
  `userType` TINYINT NOT NULL,
  `userStatus` TINYINT NOT NULL DEFAULT 1,
  `userCreatedAt` VARCHAR(45) NOT NULL,
  `userUpdatedAt` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`userId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`movie` (
  `movieId` INT NOT NULL AUTO_INCREMENT,
  `movieName` VARCHAR(45) NOT NULL,
  `movieDirector` VARCHAR(45) NOT NULL,
  `movieProducer` VARCHAR(45) NOT NULL,
  `movieClassification` VARCHAR(45) NOT NULL,
  `movieDuration` INT NOT NULL,
  `movieStatus` TINYINT NOT NULL DEFAULT 1,
  `movieCreatedAt` VARCHAR(45) NOT NULL,
  `movieUpdatedAt` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`movieId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`schedule` (
  `scheduleId` INT NOT NULL AUTO_INCREMENT,
  `scheduleStart` VARCHAR(45) NOT NULL,
  `scheduleEnd` VARCHAR(45) NOT NULL,
  `scheduleStatus` TINYINT NOT NULL DEFAULT 1,
  `scheduleCreatedAt` VARCHAR(45) NOT NULL,
  `scheduleUpdatedAt` VARCHAR(45) NOT NULL,
  `roomId` INT NOT NULL,
  PRIMARY KEY (`scheduleId`, `roomId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`room` (
  `roomId` INT NOT NULL AUTO_INCREMENT,
  `roomNumber` INT NOT NULL,
  `roomStatus` TINYINT NOT NULL DEFAULT 1,
  `roomCreatedAt` VARCHAR(45) NOT NULL,
  `roomUpdatedAt` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`roomId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`state`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`state` (
  `stateId` INT NOT NULL AUTO_INCREMENT,
  `stateName` VARCHAR(45) NOT NULL,
  `stateStatus` TINYINT NOT NULL DEFAULT 1,
  `stateCreatedAt` VARCHAR(45) NOT NULL,
  `stateUpdatedAt` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`stateId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`municipality`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`municipality` (
  `municipalityId` INT NOT NULL AUTO_INCREMENT,
  `municipalityName` VARCHAR(45) NOT NULL,
  `municipalityStatus` TINYINT NOT NULL DEFAULT 1,
  `municipalityCreatedAt` VARCHAR(45) NOT NULL,
  `municipalityUpdatedAt` VARCHAR(45) NOT NULL,
  `stateId` INT NOT NULL,
  PRIMARY KEY (`municipalityId`, `stateId`),
  INDEX `fk_municipality_state_idx` (`stateId` ASC) VISIBLE,
  CONSTRAINT `fk_municipality_state`
    FOREIGN KEY (`stateId`)
    REFERENCES `mydb`.`state` (`stateId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`assistance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`assistance` (
  `assistanceId` INT NOT NULL AUTO_INCREMENT,
  `assistanceMunicipality_fk` INT NOT NULL,
  `assistancUser_fk` INT NOT NULL,
  `assistanceSchedule_fk` INT NOT NULL,
  `assistanceStatus` TINYINT NOT NULL DEFAULT 1,
  `assistanceCreatedAt` VARCHAR(45) NOT NULL,
  `assistanceUpdatedAt` VARCHAR(45) NOT NULL,
  `movie_movieId` INT NOT NULL,
  `schedule_scheduleId` INT NOT NULL,
  `schedule_roomId` INT NOT NULL,
  `municipality_municipalityId` INT NOT NULL,
  `municipality_stateId` INT NOT NULL,
  `user_userId` INT NOT NULL,
  `room_roomId` INT NOT NULL,
  PRIMARY KEY (`assistanceId`, `movie_movieId`, `schedule_scheduleId`, `schedule_roomId`, `municipality_municipalityId`, `municipality_stateId`, `user_userId`, `room_roomId`),
  INDEX `fk_assistance_movie1_idx` (`movie_movieId` ASC) VISIBLE,
  INDEX `fk_assistance_schedule1_idx` (`schedule_scheduleId` ASC, `schedule_roomId` ASC) VISIBLE,
  INDEX `fk_assistance_municipality1_idx` (`municipality_municipalityId` ASC, `municipality_stateId` ASC) VISIBLE,
  INDEX `fk_assistance_user1_idx` (`user_userId` ASC) VISIBLE,
  INDEX `fk_assistance_room1_idx` (`room_roomId` ASC) VISIBLE,
  CONSTRAINT `fk_assistance_movie1`
    FOREIGN KEY (`movie_movieId`)
    REFERENCES `mydb`.`movie` (`movieId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_assistance_schedule1`
    FOREIGN KEY (`schedule_scheduleId` , `schedule_roomId`)
    REFERENCES `mydb`.`schedule` (`scheduleId` , `roomId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_assistance_municipality1`
    FOREIGN KEY (`municipality_municipalityId` , `municipality_stateId`)
    REFERENCES `mydb`.`municipality` (`municipalityId` , `stateId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_assistance_user1`
    FOREIGN KEY (`user_userId`)
    REFERENCES `mydb`.`user` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_assistance_room1`
    FOREIGN KEY (`room_roomId`)
    REFERENCES `mydb`.`room` (`roomId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
